### ISSUE TITLE
TODO: documentation improvements

### ISSUE THREAD

**Issue by AdeelH** [azavea/raster-vision#1505]
Follow-up to #1501 

**Major**
- [ ] Rewrite docs to emphasize the library aspect of RV (as opposed to the framework aspect).
- [ ] Rewrite README.
- [ ] Reorganize docs for better readability.
- [ ] Add more tutorial notebooks (#1459).

**Minor**
- [ ] Consider switching theme to `pydata_sphinx_theme`.
- [ ] Add dosctrings for modules.
- [ ] Ensure Google-style docstring format everywhere.
- [ ] Ensure docstrings and type hints for the most important classes/functions.
- [ ] Disambiguate `registry` and `rv_config` from their respective module names.
- [ ] Where feasible, replace `*args, **kwargs` with full list of arguments or link to the parent class's documentation.
- [ ] Consider using less automated API reference pages for modules. Example: https://github.com/scipy/scipy/blob/main/scipy/linalg/__init__.py,

**Comment by lewfish** [comment]
What do you think about making it so that you can hit a button next to the notebooks in the docs and it will open it in Google Colab? We will have to modify the notebooks to have a preamble section where we install RV and any other necessary setup.

**Comment by AdeelH** [comment]
I like that idea.

Here is an attempt:
https://github.com/azavea/raster-vision/pull/1506/commits/0e31373f5b5d9b7b21325466d557c42eb2c61261

Result:
https://raster-vision--1506.org.readthedocs.build/en/1506/tutorials/reading_labels.html

**Comment by lewfish** [comment]
Looks good!

I noticed that when searching the docs for an argument to a Config class, the page I'm actually looking for is way down in the results. It seems to show links to source code before API docs. Maybe there's a way to specify a search path of sorts. 

For example, when searching https://docs.rastervision.io/en/latest/search.html?q=max_windows, I want it to give me this link first https://docs.rastervision.io/en/latest/api_reference/_generated/rastervision.pytorch_learner.learner_config.GeoDataWindowConfig.html

**Comment by AdeelH** [comment]
Interestingly, the built-in sphinx search (which is used in local builds and PR builds) [lists the correct result as the top result](https://raster-vision--1501.org.readthedocs.build/en/1501/search.html?q=max_windows&check_keywords=yes&area=default). But the actual deployed RTD build [uses ElasticSearch](https://docs.readthedocs.io/en/stable/server-side-search.html), which returns different results. There does not seem to be a way to turn it off as far as I can tell, nor is it clear that we would want to.

There does seem to be [a configuration option to down-rank certain pages](https://docs.readthedocs.io/en/stable/config-file/v2.html#search-ranking) though, which I have now set to down-rank source code pages -- that should move the correct result up a few places. We won't know if it works until the PR is merged though.
