### ISSUE TITLE
Refactoring subtasks

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#873]
This is to track subtasks for the major refactoring of RV that is underway and which lives in `rastervision2`.

- [x] chip classification third pass:
  - [x] add validate methods for configs
  - [x] add analyze command and use raster stats
  - [x] use tensorboard in pytorch_learner
  - [x] use albumentations in pytorch_learner
- [x] add semantic segmentation
  - [x] add learner
  - [x] add pipeline
  - [x] don't do semantic segmentation in streaming fashion within scene
  - [x] cleanup vectorization
- [x] add object detection
  - [x] add learner
  - [x] add pipeline
- [x] second pass through refactor
  - [x] input validation: files exist for current command
  - [x] other input validation
  - [ ] abstract out pytorch backend config
  - [ ] don't put decorator on pydantic classes so they can be used by IDE?
  - [ ] raise error for non-4326 geojson files
  - [ ] bells and whistles on cli
  - [ ] don't hardcode /opt/data/torch-cache?
  - [ ] option for using pretrained model or not
  - [ ] local runner
- [ ] update docs
  - [ ] readthedocs
  - [ ] pydocs
  - [ ] types
  - [ ] examples repo
- [ ] update tests
  - [ ] unit tests
  - [ ] integration tests
  - [ ] update ci
- [ ] update packaging / deployment
  - [ ] setup.py / pip installation
  - [ ] rv-aws setup repo
  - [ ] slim down the Docker image

Other high-priority functionality that may be part of the next release:
- [ ] handle non-epsg:4326 GeoJSON files
- [ ] helper function to read scene out of STAC
- [ ] multiband training
- [ ] prediction pipeline for doing bulk predictions in the cloud using model bundle
- [ ] command to convert predictions and eval to STAC format
- [ ] improved documentation on some topics

**Comment by lewfish** [comment]
Closing because this is subsumed by several issues #881 #882 #883 #884
