### ISSUE TITLE
Refactoring: Second Pass

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#881]
- [x] fix config api docs not building on RTD
- [x] must have aws batch config even if rv.aws_batch plugin is not there
- [x] test ability to set config using env vars and update docs
- [x] better error message for config not found
- [x] error if non-4326 geojson files
- [x] local runner
- [x] make colors optional
- [x] check for off by one errors due to changing from 1 to 0 based class indexing
- [x] datasample shouldn't default scene ids -- should use uuid?
- [x] check scene ids are unique
- [x] error if batch size is > dataset size
- [x] pydantic validation should be manually triggered after update command is run
- [x] update validation to use pydantic optional field validation
- [x] defaults for model archs
- [x] test: resume and init weights functionality
- [x] option for using pretrained model or not
- [x] second pass through config docs to state what can be filled in automatically
- [x] elevate info on plugin structure in api docs
- [x] check that examples and pre-processing notebooks are okay due to switch to zero based indexing
- [ ] don't hardcode /opt/data/torch-cache?
- [ ] api docs enum type does not show up
- [ ] add cogify pipeline
- [ ] more safety checks to make sure configs and plugins are registered correctly
- [x] in `Learners` avoid testing for s3 directly and use `FileSystem`
