### ISSUE TITLE
Refactor: update packaging / deployment

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#884]
- [ ] setup.py / pip installation
- [ ] rv-aws setup repo
- [ ] slim down the Docker image
