### ISSUE TITLE
Leftover work from 0.12 release

### ISSUE THREAD

**Issue by lewfish** [azavea/raster-vision#960]
Here are some rough notes on lower-priority things I wanted to do in the 0.12 release, but didn't have time for. 

- [x] docker image badge broken (#1587)
- [x] code coverage broken
- ~RVPipeline -> GeoMLPipeline and rv.core -> rv.geoml?~
- [x] ability to use model bundles with plugins that aren't installed but aren't actually used by any configs (#1916)
- ~predictor is kinda inelegant and might not work with other backends~
- [ ] bad edge predictions when chip size doesn't divide prediction image size esp. on right side?
- [x] more links to RV source code in docs, esp. from class names
- ~collapse api.rst and pipeline.rst docs~
- [x] document upgrader mechanism and plugin versions (#1917)
- [x] shrink docker image if possible (#1866)
- [x] don't hardcode /opt/data/torch-cache
- [ ] more safety checks to make sure configs and plugins are registered correctly
